.. raw:: html

    <table border="0" cellspacing="0" class="latest-news">
      <tr>
        <td align="center"><font size="4">
            <strong>Latest News</strong></font>
          <p><a href="/news/october2011.html" style="text-decoration:none">
              <font color="#808080"><strong>Shen appears under<br/>Steel  Bank Common Lisp</strong></font></a></p>
          <p><img src="/_static/img/news/glossy430.jpg" width="147" height="102"></p>
          <p><a href="/news/october2011.html" style="text-decoration:none">
              <font color="#808080"><strong>Shen port to Javascript project</strong></font></a></p>
          <p><img src="http://t0.gstatic.com/images?q=tbn:ANd9GcS2sox0td8qcaxYxCKmo-Vrbh3OZ7P5RxV8-Sl7YPU_qixXosoQ" style="WIDTH: 184px; HEIGHT: 155px" id="rg_hi" class="rg_hi" data-width="184" data-height="155"></p>
        </td>
      </tr>
    </table>
